"""
File Format Investigation Utility

This script provides functionality for analyzing and understanding the format and structure
of result files generated by the jailbreak attack framework. It helps researchers inspect
the contents of these files to verify their correctness, understand their organization,
and identify any inconsistencies or issues.

Key features:
- Loading and parsing of result files in various formats (JSONL, etc.)
- Inspection of file structure and content organization
- Extraction and display of metadata and key result information
- Verification of file format compliance with expected standards
- Support for debugging issues with malformed or unexpected data formats

This utility is particularly useful during development and debugging of the framework,
when introducing new data formats, or when troubleshooting issues with result processing
in downstream analysis tools.

Usage:
    python investigate_file_format.py [options]

The script outputs detailed information about the inspected files to help understand
their format and content.
"""

import json
import sys
import glob
import os

def analyze_file_structure(file_path):
    """Analyze the structure of a single JSONL file to understand how scores are stored"""
    print(f"Analyzing file: {file_path}")
    
    with open(file_path, 'r') as f:
        lines = f.readlines()
    
    if not lines:
        print("File is empty")
        return
    
    # Parse the first line (metadata)
    try:
        metadata = json.loads(lines[0])
        print("\n===== METADATA =====")
        print(f"Original Evaluator Model: {metadata.get('original_evaluator_model', 'Not found')}")
        print(f"Current Evaluator Model: {metadata.get('evaluator_model', 'Not found')}")
        print(f"All Metadata Keys: {list(metadata.keys())}")
        
        # Check if there's any specific original score field
        original_score_field = None
        for key in metadata.keys():
            if 'original' in key.lower() and 'score' in key.lower():
                original_score_field = key
                print(f"Found potential original score field: {key}")
    except json.JSONDecodeError:
        print("Error parsing the first line as JSON")
        return
    
    # Analyze subsequent lines (interactions)
    print("\n===== INTERACTION STRUCTURE (first 2 rounds) =====")
    for i, line in enumerate(lines[1:3], 1):  # Look at first 2 rounds
        try:
            data = json.loads(line)
            print(f"\nRound {i} Keys: {list(data.keys())}")
            
            # Check if score is present
            if 'score' in data:
                print(f"Score in line {i}: {data['score']}")
            
            # Check for any original score fields
            for key in data.keys():
                if 'original' in key.lower() and 'score' in key.lower():
                    print(f"Found potential original score field in round {i}: {key} = {data[key]}")
            
        except json.JSONDecodeError:
            print(f"Error parsing line {i+1} as JSON")
    
    # Count how many interaction rounds there are
    score_count = 0
    for line in lines[1:]:  # Skip metadata
        try:
            data = json.loads(line)
            if 'score' in data:
                score_count += 1
        except json.JSONDecodeError:
            continue
    
    print(f"\nTotal rounds with scores: {score_count}")
    
    # Provide guidance based on analysis
    print("\n===== CONCLUSION =====")
    if 'original_evaluator_model' in metadata and metadata['original_evaluator_model'] == 'openai/gpt-4.1-mini':
        print("This file was originally evaluated with GPT-4.1-mini")
        print("Current scores are from GPT-4.1-nano")
        
        # Check if original scores might be stored elsewhere
        print("\nTo find the original GPT-4.1-mini scores, you might need to:")
        print("1. Check if there's a corresponding file without the _eval_gpt-4.1-nano suffix")
        print("2. Look for any fields in the metadata or rounds that contain 'original' + 'score'")
        print("3. If neither exists, you might need to infer from timestamps or naming conventions")

def main():
    """Find and analyze a sample file or use the provided file path"""
    if len(sys.argv) > 1:
        # Use the file provided as an argument
        file_path = sys.argv[1]
        if not os.path.exists(file_path):
            print(f"File not found: {file_path}")
            return
        analyze_file_structure(file_path)
    else:
        # Find a sample file
        directories = [
            "clean_results/final_runs/batch3A/crowding",
            "clean_results/final_runs/batch3A/direct_request"
        ]
        
        for directory in directories:
            files = glob.glob(os.path.join(directory, "*_eval_gpt-4.1-nano.jsonl"))
            if files:
                # Use the first file found
                analyze_file_structure(files[0])
                return
        
        print("No suitable files found for analysis")

if __name__ == "__main__":
    main() 